SlamDunkHacks/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameTickets.urls'))
]

gameTickets/urls.py
from django.urls import path
from gameTickets import views

app_name = 'gameTickets'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('tickets/<str:team_name>', views.tickets, name='tickets')
]

gameTickets/models.py
from django.db import models

# Create your models here.

gameTickets/views.py
from django.shortcuts import render
import json
from SlamDunkHacks.settings import BASE_DIR
from .getJsonData import getCoverPage, getAllDates, getData
# Create your views here.


def index(request):
    return render(request, 'index.html')


def dashboard(request):

    json_data = open(BASE_DIR / 'static' / 'CrawledData' / 'logos.json')
    data = json.load(json_data)
    return render(request, 'dashboard.html', {"teams": data})


def tickets(request, team_name):
    coverImageUrl = getCoverPage(team_name)
    dates = getAllDates(team_name)
    SH, TP, GT = getData(team_name)
    return render(request, 'tickets.html', {"name": team_name, "coverImg": coverImageUrl, "dates": dates, "StubHub": SH, "TickPick": TP, "GameTime": GT})

templates/dashboard.html
<!DOCTYPE html>
{% load static %}
{% load my_extras %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'CSS/dashboard.css' %}" type="text/css">
    <title>Document</title>
</head>
<body>
    <div class = "navbar">
        <img class = "logo"  src="{% static 'Images/logo.png' %}" alt="">
        <nav>
            <ul>
                <li><a href="{% url 'gameTickets:index' %}">HOME</a></li>
                <li><a id = "about" href="#">ABOUT</a></li>
            </ul>
        </nav>
    </div>
    
    <div class = "container">
        <h2>All Teams Tickets</h2>
        <div id="card-container" class = "row">
            {% for team in teams %}
                <div  class = "col-md-4 my-col">
                    <div class="card-container">
                        <div class="card">
                            <div class="imgBx">
                                <img src="{{teams|ind:team}}">
                            </div>
                            <div class="contentBx">
                                <h2>{{ team }}</h2>
                                <a href="{% url 'gameTickets:tickets' team_name=team %}">Get Tickets</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
    <!-- <script src="{% static 'JS/dashboard.js' %}"></script> -->
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'CSS/styles.css' %}">
    <title>Basketball Tickets!</title>

<!-- logo url = <img id = "logo"  src="{% static 'Images/logo.jpeg' %}" alt=""> -->
</head>
<body>
    <div class="navbar">
        <img class = "logo"  src="{% static 'Images/logo.png' %}" alt="">
        <nav>
            <ul>
                <li><a href="{% url 'gameTickets:index' %}">HOME</a></li>
                <li><a id = "about" href="#">ABOUT</a></li>
            </ul>
        </nav>
    </div>
    
    <div class = "row">
        <div class = "col">
            <h1>NBA TICKET EXPLORER</h1>
        </div>
        <div class = "col">
            <a href="{% url 'gameTickets:dashboard' %}">
            <button type="button" class="btn">Explore</button></a>
        </div>
    </div>

</body>

</html>

templates/tickets.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load my_extras %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'CSS/tickets_styles.css' %}">
    <title>Basketball Tickets</title>
</head>
<body>
    <div class = "navbar">
        <img class = "logo"  src="{% static 'Images/logo.png' %}" alt="">
        <nav>
            <ul>
                <li><a href="{% url 'gameTickets:index' %}">HOME</a></li>
                <li><a id = "about" href="#">ABOUT</a></li>
            </ul>
        </nav>
    </div>
    <div style="background-image: url('{{coverImg}}')" class = "cover_image"></div>
    <h1>{{ name }} Tickets</h1>
    <div class = "container">
        {% for date in dates %}
        <div class = "row">
                <h3 class = "date">{{date}}</h3>
                {% if StubHub|ind:date %}
                <div class = "col-md-4">
                        <a href="https://www.stubhub.com/nba-tickets/grouping/115/" target="_blank" class="data-card">
                        <h3>{{ StubHub|ind:date|ind:"title" }}</h3>
                        <h4>From {{StubHub|ind:date|ind:"price"}}</h4>
                        <p>{{StubHub|ind:date|ind:"location"}}<br>stubhub.com</p>
                        <span class="link-text">
                            View Provider
                            <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
                    </svg>
                        </span>
                        </a>
                </div>
                {% endif %}
                {% if TickPick|ind:date %}
                <div class = "col-md-4">
                    <a href="https://www.tickpick.com/nba-tickets/" target="_blank" class="data-card">
                    <h3>{{ TickPick|ind:date|ind:"title" }}</h3>
                    <h4>From {{TickPick|ind:date|ind:"price"}}</h4>
                    <p>{{TickPick|ind:date|ind:"location"}}<br>tickpick.com</p>
                    <span class="link-text">
                        View All Providers
                        <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
                    </svg>
                        </span>
                        </a>
                </div>
                {% endif %}
                {% if GameTime|ind:date %}
                <div class = "col-md-4">
                    <a href="https://gametime.co/nba-basketball-tickets" target="_blank" class="data-card">
                    <h3>{{ GameTime|ind:date|ind:"title" }}</h3>
                    <h4>From {{GameTime|ind:date|ind:"price"}}</h4>
                    <p>{{GameTime|ind:date|ind:"location"}}<br>gametime.co</p>
                    <span class="link-text">
                        View All Providers
                        <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
                    </svg>
                        </span>
                        </a>
                </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
        
   

</body>
</html>